services:
  finapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    volumes:
      - ./key.json:/secrets/key.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/key.json
      APP_ENV: production
    ports:
      - "8080:8080"
    networks:
      - backend-net
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /app

networks:
  backend-net:
    driver: bridge
