name: Backend CI/CD
on:
  push:
    branches:
      - main
      - heaven
  pull_request:
    branches:
      - main

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Integration tests with Firestore emulartor
        run: |
          docker compose \
            -f compose.ci.yml \
            -f compose.test.yml \
            up --build --abort-on-container-exit

      - name: Clean up
        if: always()
        run: |
          docker compose \
            -f compose.ci.yml \
            -f compose.test.yml \
            down -v

  backend-cd:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: backend-ci
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: backend
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authorize Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Who am I?
        run: |
          gcloud auth list
          gcloud config get-value account

      - name: Build and push Docker image
        run: |
          gcloud builds submit . \
            --service-account=projects/${{ secrets.GCP_PROJECT_ID }}/serviceAccounts/${{ secrets.GCP_SA_EMAIL }} \
            --gcs-log-dir=gs://${{ secrets.GCP_PROJECT_ID }}-cloudbuild-logs \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest

      - name: Deploy to Cloud Run
        env:
          APP_ENV: production
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud run deploy fin-app-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SA_EMAIL }} \
            --memory 4Gi \
            --set-env-vars "APP_ENV=${APP_ENV},GCP_PROJECT_ID=${GCP_PROJECT_ID}"
